"""empty message

Revision ID: 166ab371ba56
Revises: e78eabb005dd
Create Date: 2022-08-12 13:26:09.865752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '166ab371ba56'
down_revision = 'e78eabb005dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
