"""empty message

Revision ID: 2db5e049364b
Revises: e2245b0a93ad
Create Date: 2022-08-13 16:22:45.577929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2db5e049364b'
down_revision = 'e2245b0a93ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'created_date')
    # ### end Alembic commands ###
