"""empty message

Revision ID: 33a6ee6d1f76
Revises: 96f28f125bca
Create Date: 2022-08-12 02:53:11.429206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33a6ee6d1f76'
down_revision = '96f28f125bca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'state')
    op.drop_column('venues', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('venues', sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
