"""empty message

Revision ID: 81672cea6fcc
Revises: 60d9388f50cc
Create Date: 2022-08-12 02:50:43.395201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81672cea6fcc'
down_revision = '60d9388f50cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('area_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'venues', 'areas', ['area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venues', type_='foreignkey')
    op.drop_column('venues', 'area_id')
    # ### end Alembic commands ###
