"""empty message

Revision ID: 96f28f125bca
Revises: 81672cea6fcc
Create Date: 2022-08-12 02:51:31.341571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96f28f125bca'
down_revision = '81672cea6fcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('area_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'venues', 'areas', ['area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venues', type_='foreignkey')
    op.drop_column('venues', 'area_id')
    # ### end Alembic commands ###
