"""empty message

Revision ID: e327ca8c58e6
Revises: 9eea5aaf8270
Create Date: 2022-08-12 00:52:35.082333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e327ca8c58e6'
down_revision = '9eea5aaf8270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'website_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('venues', 'seeking_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'seeking_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('venues', 'website_link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
